DROP TABLE IF EXISTS zno;
CREATE TABLE zno (
                Year SMALLINT,
                OutID UUID PRIMARY KEY,
                Birth SMALLINT NOT NULL,
                SexTypeName VARCHAR(10) NOT NULL,
                RegName VARCHAR(35) NOT NULL,
                AreaName VARCHAR(35) NOT NULL,
                TerName VARCHAR(40) NOT NULL,
                RegTypeName VARCHAR(100) NOT NULL,
                TerTypeName VARCHAR(5) NOT NULL,
                ClassProfileName VARCHAR(40),
                ClassLangName VARCHAR(15),
                EOName VARCHAR(300), 
                EOTypeName VARCHAR(70),
                EORegName VARCHAR(35),
                EOAreaName VARCHAR(50),
                EOTerName VARCHAR(50),
                EOParent VARCHAR(250),
                
                UkrTest VARCHAR(35),
                UkrTestStatus VARCHAR(35),
                UkrBall100 FLOAT(2),
                UkrBall12 VARCHAR(35),
                UrkBall SMALLINT, 
                UkrAdaptScale SMALLINT,
                UkrPTName VARCHAR(300),
                UkrPTRegName VARCHAR(200),
                UkrPTAreaName VARCHAR(200),
                UkrPTTerName VARCHAR(50),

                HistTest VARCHAR(35),
                HistLang VARCHAR(20),
                HistTestStatus VARCHAR(35),
                HistBall100 FLOAT(2),
                HistBall12 VARCHAR(35),
                HistBall SMALLINT, 
                HistPTName VARCHAR(300),
                HistPTRegName VARCHAR(200),
                HistPTAreaName VARCHAR(200),
                HistPTTerName VARCHAR(50),
                
                MathTest VARCHAR(35),
                MathLang VARCHAR(20),
                MathTestStatus VARCHAR(35),
                MathBall100 FLOAT(2),
                MathBall12 VARCHAR(35),
                MathBall SMALLINT, 
                MathPTName VARCHAR(300),
                MathPTRegName VARCHAR(200),
                MathPTAreaName VARCHAR(200),
                MathPTTerName VARCHAR(50),

                PhysTest VARCHAR(35),
                PhysLang VARCHAR(20),
                PhysTestStatus VARCHAR(35),
                PhysBall100 FLOAT(2),
                PhysBall12 VARCHAR(35),
                PhysBall SMALLINT, 
                PhysPTName VARCHAR(300),
                PhysPTRegName VARCHAR(200),
                PhysPTAreaName VARCHAR(200),
                PhysPTTerName VARCHAR(50),

                ChemTest VARCHAR(35),
                ChemLang VARCHAR(20),
                ChemTestStatus VARCHAR(35),
                ChemBall100 FLOAT(2),
                ChemBall12 VARCHAR(35),
                ChemBall SMALLINT, 
                ChemPTName VARCHAR(300),
                ChemPTRegName VARCHAR(200),
                ChemPTAreaName VARCHAR(200),
                ChemPTTerName VARCHAR(50),

                BioTest VARCHAR(35),
                BioLang VARCHAR(20),
                BioTestStatus VARCHAR(35),
                BioBall100 FLOAT(2),
                BioBall12 VARCHAR(35),
                BioBall SMALLINT, 
                BioPTName VARCHAR(300),
                BioPTRegName VARCHAR(200),
                BioPTAreaName VARCHAR(200),
                BioPTTerName VARCHAR(50),

                GeoTest VARCHAR(35),
                GeoLang VARCHAR(20),
                GeoTestStatus VARCHAR(35),
                GeoBall100 FLOAT(2),
                GeoBall12 VARCHAR(35),
                GeoBall SMALLINT, 
                GeoPTName VARCHAR(300),
                GeoPTRegName VARCHAR(200),
                GeoPTAreaName VARCHAR(200),
                GeoPTTerName VARCHAR(50),

                EngTest VARCHAR(35),
                EngLang VARCHAR(20),
                EngTestStatus VARCHAR(35),
                EngBall100 FLOAT(2),
                EngBall12 VARCHAR(35),
                EngBall VARCHAR(35), 
                EngPTName VARCHAR(300),
                EngPTRegName VARCHAR(200),
                EngPTAreaName VARCHAR(200),
                EngPTTerName VARCHAR(50),

                FraTest VARCHAR(35),
                FraLang VARCHAR(20),
                FraTestStatus VARCHAR(35),
                FraBall100 FLOAT(2),
                FraBall12 VARCHAR(35),
                FraBall SMALLINT, 
                FraPTName VARCHAR(300),
                FraPTRegName VARCHAR(200),
                FraPTAreaName VARCHAR(200),
                FraPTTerName VARCHAR(50),

                DeuTest VARCHAR(35),
                DeuLang VARCHAR(20),
                DeuTestStatus VARCHAR(35),
                DeuBall100 FLOAT(2),
                DeuBall12 VARCHAR(35),
                DeuBall SMALLINT, 
                DeuPTName VARCHAR(300),
                DeuPTRegName VARCHAR(200),
                DeuPTAreaName VARCHAR(200),
                DeuPTTerName VARCHAR(50),

                SpaTest VARCHAR(35),
                SpaLang VARCHAR(20),
                SpaTestStatus VARCHAR(35),
                SpaBall100 FLOAT(2),
                SpaBall12 VARCHAR(35),
                SpaBall SMALLINT, 
                SpaPTName VARCHAR(200),
                SpaPTRegName VARCHAR(200),
                SpaPTAreaName VARCHAR(200),
                SpaPTTerName VARCHAR(50)
);